### PR TITLE
chore: tidy examples

### PR DESCRIPTION
**Pull request by needim**
This PR expands the monorepo by including the examples folder in the project scope.

- Examples Integration:

	- Added examples to the monorepo scope so dependencies are now installed automatically.
	- Updated examples to use workspace packages (workspace:*).
	- Bumped examples dependencies
	- Added @sqlite.org/sqlite-wasm to exclude array for vite projects.

- Script Changes:

	- Modified existing scripts to keep the standard development workflow unchanged.
	- Added two new scripts: examples:dev for development and examples:build for building examples.

- Naming Convention:

	- Renamed examples to follow a consistent naming convention.
	

These updates enhance the development flow by ensuring examples are easily maintained and integrated.

### CODE REVIEW

**Comment by steida** [comment]
Wow, thank you, but I'm not sure we want that. The reason the examples were separated was that people could just copy the directory and start using it. Also, separating examples from the Evolu monorepo allows them to be tested in isolation. For example, in Stackblitz or Codesandbox. I think we should isolate them even more if possible, so deps installed in examples dirs do not interfere with Evolu monorepo deps. What do you think? On the contrary, having examples in monorepo means we ensure their deps are actual, and we can test all examples with actual Evolu before a release.

Do examples within the monorepo work with Stackblitz?

**Comment by needim** [comment]
Thanks for the feedback! I see where you're coming from about keeping examples separate, but I think having them in the monorepo is actually beneficial for our development process. Here’s why:

1. **Improved Developer Experience:**
   - Having examples in the monorepo is great for developer experience (DX). It makes it easier for us to ensure that all examples are up-to-date with the latest changes in the codebase, which is super helpful, especially when we're working on multiple packages like Solid and Vue.

2. **User-Friendly Approach:**
   - For users who want to try Evolu without diving into the whole monorepo, we could create a CLI tool, like `npx create-evolu`, that lets them spin up examples quickly. This way, they get the benefits of standalone examples without needing to extract them manually.

3. **Testing in Stackblitz/Codesandbox:**
   - We should definitely check how the examples work in environments like Stackblitz and Codesandbox when integrated with the monorepo. If it’s an issue, maybe we can provide a way to export them for these platforms easily.

Overall, keeping the examples in the monorepo helps us with consistent testing and development, while a CLI tool could address user needs for easy access. What do you think?

--- 

Feel free to tweak this as needed!

**Comment by steida** [comment]
Astro has examples as part of the monorepo, but examples use Astro from NPM. Let's do the same. We should also have the same readme like this https://github.com/withastro/astro/blob/main/examples/README.md

With this approach, Evolu CLI can download an example from /examples, and Stackblitz would work, too.

Readme.md should also have instructions on how to develop Evolu integration. Basically, just replace Evolu dependency in an example package.json from NPM to monorepo.

What do you think?

**Review by steida — APPROVED** [review]
Perfect work, thank you!

**Comment by needim** [comment]
I will create another PR for cli. 👍

**Comment by steida** [comment]
Check Effect: https://github.com/effect-ts/effect/tree/main/packages/cli; I think it would be nice to use it. Feel free to ask me anything about Effect on Discord.

**Pull request merged**
